eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    enabled: true
    service-url:
      defaultZone: http://eureka-0.eureka-service.default.svc.cluster.local:8761/eureka

spring:
  datasource:
    url: ${RESTAURANT_DB_URL}
    username: ${SQL_DB_USERNAME}
    password: ${SQL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver